version: "3.7"

x-env: &env
  REDIS_URL: redis://redis:6381
  GLOWFIC_DATABASE_HOST: postgres:5434
  GLOWFIC_DATABASE_USER: postgres
  GLOWFIC_DATABASE_PASS: postgres
x-svc: &svc
  build: .
  image: glowfic
  links:
    - redis
    - postgres
  volumes:
    - .:/code
    - bundler-volume:/usr/local/bundle
    - webdrivers:/root/.webdrivers # caches webdrivers for selenium feature specs

services:
  web:
    <<: *svc
    ports:
      - "3002:3000"
    command: bin/rails s
    environment:
      <<: *env
      BIND_HOST: 0.0.0.0
  worker:
    <<: *svc
    command: bundle exec rake resque:work
    environment:
      <<: *env
      TERM_CHILD: 1
      RESQUE_TERM_TIMEOUT: 7
      QUEUES: mailer,notifier,high,*
  redis:
    image: redis:4.0-alpine
    ports:
      - 6381:6379
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  bundler-volume:
  postgres-data:
  webdrivers:
